# Generated by Django 4.1.2 on 2022-10-15 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('reported_by', models.CharField(default='username', max_length=20, primary_key=True, serialize=False)),
                ('complaint_name', models.CharField(max_length=100, null=True)),
                ('about_complaint', models.CharField(max_length=200, null=True)),
                ('dateandtime', models.DateTimeField(blank=True, default='')),
                ('exact_location', models.TextField(max_length=500, null=True)),
                ('action_taken', models.TextField(max_length=500, null=True)),
            ],
        ),
    ]
