# Generated by Django 4.1.2 on 2022-10-15 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
