# Generated by Django 4.1.2 on 2022-10-15 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_remove_complaint_id_alter_complaint_reported_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='reported_by',
            field=models.CharField(default='username', max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
