# Generated by Django 4.1.2 on 2022-10-15 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0006_complaint_id_alter_complaint_reported_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
